### ISSUE TITLE
Advisory: How may I debug a Python code of WASM component?

### ISSUE THREAD

**Issue by yophilav** [bytecodealliance/componentize-py#127]
Hi componentize-py folks!

Thank you for a great presentation at WASMCON a while ago! I just now catching up with your nifty tool.
What is your debugging guideline for a Python-turn-WASM component?
I'm investigating a feasibility if somehow I could ~~magically~~ debug the python code of a WASM component.

I ran a quick experiement where I built a `lib.wasm` from Python code `lib.py` which export `add()` function that has an embedded breakpoint using `componentize-py`. 
The `lib.wasm` component is then loaded into a Rust host app using `wasmtime`. The goal here is to see if I could set a breakpoint for the python application code.
### Dependency 
    - wasmtime 25.0.2
    - componentize-py 0.14.0
    - Python 3.8.10

main.rs
``` 
use wasmtime::*;

fn main() ->  wasmtime::Result<()> {
    let mut config = Config::new();
    config.debug_info(true);

    let engine = Engine::new(&config)?;
    
    let bytes = std::fs::read("<path/to/lib.wasm>")?;
    let component = wasmtime::component::Component::new(&engine, bytes)?;

    let linker = wasmtime::component::Linker::new(&engine);
    let mut store = Store::new(&engine, ());

    let instance = linker.instantiate(&mut store, &component)?;

    let add = instance.get_typed_func::<(i32, i32), (i32,)>(&mut store, "add")?;
    let result = add.call(&mut store, (20,22))?;
    println!("Result from add module: {:?}", result.0);

    Ok(())
}
```

lib.wit
```
package example:bearmath;
world bearmath {
  export add: func(l: s32, r: s32) -> s32;
}
```

lib.py
```
import bearmath
import pdb
class Bearmath(bearmath.Bearmath):
    def add(self, l, r) -> int:
        x = l + r

        # Attempt to programatically set a breakpoint / trace here.
        pdb.set_trace()

        return x
```

After all the files have been created, I then run `componentize-py -d lib.wit -w bearmath componentize --stub-wasi lib -o lib.wasm` to create `lib.wasm`. Then build and run the Rust program with `cargo run`.
Unfortunately, it didn't work and crash with `wasm trap: wasm 'unreachable' instruction executed`. Even though, I can see with `wasm-tools print --skeleton ./lib.wasm` that there is `add()` export and the WASM file has debug symbol enabled.

So... I'm writing to you on what's your thought on the debugging story for a WASM component. I'm new to Python and this development space. Maybe the scenario is silly and a developer should debug their code in Python before turning into a WASM component. Anyhow, I really appreciate any input you may have on the topic! :smiley:

Thank you so much,
Bear

**Comment by dicej** [comment]
Hi @yophilav.  Thanks for opening this issue.

I'll admit I hadn't tried using `pdb` before (with or without Wasm); I'm also new to Python.  However, I just tried it and it seems to work okay for me, mostly.  Here's what I did (from inside a clone of this repo):

```
 $ mkdir test
 $ cd test
 $ cat >app.py <<EOF
from command import exports
import pdb

class Run(exports.Run):
    def run(self) -> None:
        print("Hello, world!")
        pdb.set_trace()
        print("and hello again")
EOF
 $ python3 -m venv .venv
 $ source .venv/bin/activate
(.venv)  $ pip install componentize-py
(.venv)  $ cargo install wasmtime-cli
(.venv)  $ curl -OL https://github.com/WebAssembly/wasi-cli/archive/refs/tags/v0.2.2.tar.gz
(.venv)  $ tar xf v0.2.2.tar.gz
(.venv)  $ componentize-py -d wasi-cli-0.2.2/wit -w wasi:cli/command@0.2.2 componentize app -o cli.wasm
(.venv)  $ wasmtime run cli.wasm
Hello, world!
> /0/app.py(8)run()
(Pdb) p Run
<class 'app.Run'>
(Pdb) p pdb
<module 'pdb' from '/python/pdb.py'>
(Pdb) exit
Traceback (most recent call last):
  File "/0/app.py", line 8, in run
  File "/python/bdb.py", line 90, in trace_dispatch
  File "/python/bdb.py", line 115, in dispatch_line
bdb.BdbQuit
thread '<unnamed>' panicked at runtime/src/lib.rs:499:25:
Python function threw an unexpected exception
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: failed to run main module `cli.wasm`

Caused by:
    0: failed to invoke `run` function
    1: error while executing at wasm backtrace:
           0: 0xb72d22 - libcomponentize_py_runtime.so!__rust_start_panic
           1: 0xb6c1a7 - libcomponentize_py_runtime.so!rust_panic
           2: 0xb6c17a - libcomponentize_py_runtime.so!std::panicking::rust_panic_with_hook::hdd590f21ce188187
           3: 0xb5e38a - libcomponentize_py_runtime.so!std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::hd832f8b925ef66b0
           4: 0xb5e2b2 - libcomponentize_py_runtime.so!std::sys::backtrace::__rust_end_short_backtrace::h7a76da6cd7a8845a
           5: 0xb6ba4c - libcomponentize_py_runtime.so!rust_begin_unwind
           6: 0xb9f8a5 - libcomponentize_py_runtime.so!core::panicking::panic_fmt::h84bfbbb850b16446
           7: 0xaed6c8 - libcomponentize_py_runtime.so!componentize-py#Dispatch
           8: 0x223b376 - libcomponentize_py_bindings.so!wasi:cli/run@0.2.2#run-export
    2: wasm trap: wasm `unreachable` instruction executed
```

As you can see, `pdb` worked until I exited using Ctrl-D, at which point it hit an `unreachable`.  As indicated by the error message ("Python function threw an unexpected exception"), it looks like `pdb` threw an exception from the `run` function I exported in my app, which the `componentize-py` runtime didn't know how to convert to a result at the component boundary, so it did the only thing it could: it trapped.  We can fix that by wrapping the body of `run` in `try/except`:

```
(.venv)  $ cat >app.py <<EOF
> from command import exports
import pdb

class Run(exports.Run):
    def run(self) -> None:
        try:
            print("Hello, world!")
            pdb.set_trace()
            print("and hello again")
        except:
            return
EOF
(.venv)  $ componentize-py -d wasi-cli-0.2.2/wit -w wasi:cli/command@0.2.2 componentize app -o cli.wasm
Component built successfully
(.venv)  $ wasmtime run cli.wasm
Hello, world!
> /0/app.py(9)run()
(Pdb) exit
(.venv)  $
```

Hope that helps!

**Comment by dicej** [comment]
BTW, your `main.rs` doesn't use `wasmtime-wasi`, so things like stdio won't work, meaning `pdb` won't have any way to provide an interactive debug session.  So you'll want to use `wasmtime-wasi` there and make sure you're not using the `--stub-wasi` option to `componentize-py` when building your component.

**Comment by yophilav** [comment]
Thank you, that's very cool! Let me try to repoduce your result and see if I can get a debug session going through a host app.

**Comment by yophilav** [comment]
Hello @dicej,
Could help elaborate on how to use WASI agsint Wasmtime `Component` please?
I have read through the component model docs, and went through a couple examples from Wasmtime for [WASI](https://github.com/bytecodealliance/wasmtime/blob/main/examples/wasi/main.rs), and [Component](https://docs.wasmtime.dev/api/wasmtime/component/index.html#example-usage). Then I setup a program as follows: 

main.rs:
```
fn main() ->  wasmtime::Result<()> {
    let mut config = Config::new();
    config.debug_info(true);
    config.wasm_component_model(true);

    let engine: Engine = Engine::new(&config)?;
    
    // LOAD WASM AS COMPONENT
    let bytes = std::fs::read("<path/to/lib.wasm>")?;
    let component = Component::new(&engine, bytes)?;

    let wasi = WasiCtxBuilder::new()
        .inherit_stdio()
        .inherit_args()?
        .build();

    let mut store = Store::new(&engine, wasi);

    let linker = wasmtime::component::Linker::new(&engine);
    wasi_common::sync::add_to_linker(&mut linker, |s| s)?;
    // let result = linker
    //     .get_default(&mut store, "add")?
    //     .typed::<(i32, i32), (i32,)>(&store)?
    //     .call(&mut store, (20,22))?;

    let instance = linker.instantiate(&mut store, &component)?;
    let add_fnx = instance.get_typed_func::<(i32, i32), (i32,)>(&mut store, "add")?;
    let result = add_fnx.call(&mut store, (22, 20))?;
    println!("Result from add module: {:?}", result.0);
    Ok(())
}
```

This result in Rust compilation issue:
```
yophilav@Pc:~/tinykube/bear_hostwasm$ cargo build
   Compiling bear_hostwasm v0.1.0 (/home/yophilav/tinykube/bear_hostwasm)
error[E0308]: mismatched types
   --> bear_hostwasm/src/main.rs:26:38
    |
26  |     wasi_common::sync::add_to_linker(&mut linker, |s| s)?;
    |     -------------------------------- ^^^^^^^^^^^ expected `wasmtime::Linker<_>`, found `wasmtime::component::Linker<_>`
    |     |
    |     arguments to this function are incorrect
    |
    = note: expected mutable reference `&mut wasmtime::Linker<_>`
               found mutable reference `&mut wasmtime::component::Linker<_>
```

I know that I shouldn't use the Linker of a `Module` against `Component`, but I also don't know how to bridge the gap.

PS. I have also commented out the line and pretend that everything is a `Component`. It compiled to then be (unsurprisingly) error-ed out with 
```
Error: component imports instance `wasi:cli/environment@0.2.0`, but a matching implementation was not found in the linker

Caused by:
    0: instance export `get-environment` has the wrong type
    1: function implementation is missing
```

Thank you for your insights!

**Comment by dicej** [comment]
Yeah, the WASI example you linked to is out-of-date; it's using WASIp1 instead of WASIp2.  You'll want to use the WASIp2 bindings in `wasmtime_wasi` and follow [these instructions](https://docs.rs/wasmtime-wasi/latest/wasmtime_wasi/#examples).

Here's a somewhat complete example: https://github.com/bytecodealliance/wasmtime/blob/main/crates/wasi-config/tests/main.rs

**Comment by yophilav** [comment]
Hey @dicej,
Hope you had a good thanksgiving! I updated my host app to be using WASI 28.0.0. I can built those as expected.
However, I ran into the `BdbQuit` exception right away when `pdb.set_trace()` was called. 
Is there any specific in WASI config to setup to have it launch PDB interactive terminal?

I repurposed the `add()` to have it return the exception type as a string for a debugging purpose. 
My setup is as follows:
lib.py
```
import bearmath
import pdb
class Bearmath(bearmath.Bearmath):
    def add(self, l, r) -> str:
        try:
            x = l + r
            pdb.set_trace()
            return str(x)
        except Exception as e:
            return str(type(e).__name__)
```
The lib.py was componentized using `componentize-py -d lib.wit -w bearmath componentize lib -o lib.wasm`

Then in my Rust code from main:
main.rs
```
use wasmtime::{
    component::{Component, Linker, ResourceTable},
    Config, Engine, Store,
};

use wasmtime_wasi::{add_to_linker_sync, WasiCtx, WasiCtxBuilder, WasiView};

struct Ctx {
    table: ResourceTable,
    wasi_ctx: WasiCtx,
}

impl WasiView for Ctx {
    fn table(&mut self) -> &mut ResourceTable {
        &mut self.table
    }

    fn ctx(&mut self) -> &mut WasiCtx {
        &mut self.wasi_ctx
    }
}


fn main() ->  wasmtime::Result<()> {

    let mut config = Config::new();
    config.debug_info(true);
    config.wasm_component_model(true);

    let engine: Engine = Engine::new(&config)?;
    
    let path = "<path/to/lib.wasm>";
    let component = Component::from_file(&engine, path)?;
    
    let mut linker = Linker::new(&engine);
    add_to_linker_sync(&mut linker)?;

    let ctx = Ctx {
        table: ResourceTable::new(),
        wasi_ctx: WasiCtxBuilder::new().build(),
    };
    let mut store = Store::new(&engine, ctx);

    let instance = linker.instantiate(&mut store, &component)?;
    let add_fnx = instance.get_typed_func::<(i32, i32), (String,)>(&mut store, "add")?;
    let result = add_fnx.call(&mut store, (22, 20))?;

    println!("Result from add module: {:?}", result.0);

    Ok(())
}
```

**Comment by dicej** [comment]
Try adding a `.inherit_stdio()` call between `WasiCtxBuilder::new()` and `.build()`.

**Comment by yophilav** [comment]
Hi @dicej , 

Hope all is well! I have a few more questions in the same train of thought. 
Generally, a python script can be run against PDB using CLI `python -m pdb ./component.py`. If the `component.py` is then got turn into a wasm file, is there a wasmtime command that allows the underlying python to be launched against the PDB? The closest thing I can see in the documentation is `wasmtime run --invoke 'initialize("hello")' foo.wasm` but that isn't a thing for a given component. 

Thank you,
Bear

**Comment by dicej** [comment]
I don't know of any equivalent to the `-m pdb` argument to `python` for components.  Wasmtime doesn't know anything about Python or PDB, and it doesn't know that the component you give it happens to be a componentized Python script.  The only way I can think of is to add a command line option _inside_ the script before you componentize it.

For example:

```shell
cat >app.py <<EOF
from command import exports
from command.imports.environment import get_arguments
import pdb

class Run(exports.Run):
    def run(self) -> None:
        if "--pdb" in get_arguments():
            pdb.set_trace()
        print("Hello, world!")
EOF
componentize-py -d $PATH_TO_COMPONENTIZE_PY_SOURCE/wit -w wasi:cli/command@0.2.0 componentize app -o cli.wasm
wasmtime run cli.wasm --pdb
```

**Comment by yophilav** [comment]
Thank you, @dicej
