### ISSUE TITLE
[bug] Incorrect bindings generation

### ISSUE THREAD

**Issue by Siffran** [bytecodealliance/componentize-py#134]
Hello :)

I'm having an issue with how componentize.py generate bindings.

I have the following dataflow.wit file

```
package dataflow:processor;

world data-flow-processor {

    enum frame-type {
        CAN,
        LIN,
        UNKNOWN
    }

    record frame {
        frame-type: frame-type,
        id: s32,
        channel-no: s32,
        source-id: string,
        source-name: string,
        data: list<u8>,
        data-length: s32,
        dlc: s32,
        flag: s32,
        time: f64
    }

    import output: func(frame: frame) -> ();
}
```

If I generate bindings with `componentize-py -d dataflow.wit bindings .` the following `__init__.py` is generated:
```python
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from .types import Result, Ok, Err, Some


def output(frame: Frame) -> None:
    raise NotImplementedError


class FrameType(Enum):
    CAN = 0
    LIN = 1
    UNKNOWN = 2

@dataclass
class Frame:
    frame_type: FrameType
    id: int
    channel_no: int
    source_id: str
    source_name: str
    data: bytes
    data_length: int
    dlc: int
    flag: int
    time: float

class DataFlowProcessor(Protocol):
    pass
```

As you can see the `output` function is declared before the `Frame` class later producing the following error when I try to create my component:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\examples\python\basic\venv\Scripts\componentize-py.exe\__main__.py", line 7, in <module>
    sys.exit(script())
             ~~~~~~^^
AssertionError: Traceback (most recent call last):
  File "/0/basic.py", line 1, in <module>
    from data_flow_processor import Frame, FrameType
  File "/world/data_flow_processor/__init__.py", line 12, in <module>
    def output(frame: Frame) -> None:
                      ^^^^^
NameError: name 'Frame' is not defined


Caused by:
    NameError: name 'Frame' is not defined
```

Is this a bug or does anyone know any workaround? Thanks in advance :D

**Comment by dicej** [comment]
Hi @Siffran -- thanks for reporting this.  It definitely looks like a bug; I'll investigate it this morning.
